<template>
  <div class="table-editor">
    <el-card>
      <template #header>
        <div class="card-header">
          <div>
            <el-breadcrumb separator="/">
              <el-breadcrumb-item :to="{ path: '/tables' }">Таблицы</el-breadcrumb-item>
              <el-breadcrumb-item>{{ tableName }}</el-breadcrumb-item>
            </el-breadcrumb>
          </div>
          <div class="header-actions">
            <el-button type="primary" :icon="Plus" @click="handleAdd">
              Добавить запись
            </el-button>
            <el-button :icon="Refresh" @click="loadData">Обновить</el-button>
          </div>
        </div>
      </template>

      <!-- Filters -->
      <div class="filters" v-if="columns.length > 0">
        <el-input
          v-model="searchQuery"
          placeholder="Поиск..."
          :prefix-icon="Search"
          style="width: 300px; margin-right: 10px;"
          clearable
        />
        <el-select
          v-model="selectedColumn"
          placeholder="Колонка для поиска"
          style="width: 200px; margin-right: 10px;"
        >
          <el-option
            v-for="col in columns"
            :key="col.column_name"
            :label="col.column_name"
            :value="col.column_name"
          />
        </el-select>
      </div>

      <!-- Data Table -->
      <el-table
        v-loading="loading"
        :data="tableData"
        style="width: 100%; margin-top: 20px;"
        border
        :row-style="{ maxHeight: '60px' }"
        :cell-style="{ padding: '8px' }"
      >
        <el-table-column
          v-for="column in columns"
          :key="column.column_name"
          :prop="column.column_name"
          :min-width="150"
        >
          <template #header>
            <div 
              @click="handleSort(column.column_name)"
              style="cursor: pointer; user-select: none; display: flex; align-items: center; gap: 5px;"
            >
              <span>{{ column.column_name }}</span>
              <span v-if="sortColumn === column.column_name">
                <span v-if="sortOrder === 'asc'">↑</span>
                <span v-else-if="sortOrder === 'desc'">↓</span>
              </span>
            </div>
          </template>
          <template #default="{ row, $index }">
            <div 
              v-if="expandedCells.has(`${$index}-${column.column_name}`)"
              class="table-cell-expanded"
            >
              {{ formatValue(row[column.column_name]) }}
              <el-icon 
                class="expand-icon"
                @click="toggleCellExpansion($index, column.column_name)"
                style="cursor: pointer; margin-left: 8px;"
              >
                <component :is="'ArrowUp'" />
              </el-icon>
            </div>
            <el-tooltip 
              v-else
              :content="String(row[column.column_name])"
              placement="top"
              :disabled="!isTextTruncated(`${$index}-${column.column_name}`)"
              popper-class="table-tooltip"
            >
              <div 
                :ref="el => { if (el) cellRefs[`${$index}-${column.column_name}`] = el }"
                class="table-cell-content"
                @click="toggleCellExpansion($index, column.column_name)"
                style="cursor: pointer;"
              >
                {{ formatValue(row[column.column_name]) }}
              </div>
            </el-tooltip>
          </template>
        </el-table-column>
        
        <el-table-column label="Действия" width="150" fixed="right">
          <template #default="{ row }">
            <el-button text type="primary" :icon="Edit" @click="handleEdit(row)">
              Изменить
            </el-button>
            <el-button text type="danger" :icon="Delete" @click="handleDelete(row)">
              Удалить
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <!-- Pagination -->
      <el-pagination
        v-if="pagination.total > 0"
        v-model:current-page="pagination.page"
        v-model:page-size="pagination.limit"
        :total="pagination.total"
        :page-sizes="[10, 25, 50, 100]"
        layout="total, sizes, prev, pager, next, jumper"
        style="margin-top: 20px; justify-content: center;"
        @current-change="loadData"
        @size-change="loadData"
      />
    </el-card>

    <!-- Edit/Add Dialog -->
    <el-dialog
      v-model="dialogVisible"
      :title="dialogMode === 'edit' ? 'Редактировать запись' : 'Добавить запись'"
      width="600px"
    >
      <el-form :model="formData" label-width="150px">
        <el-form-item
          v-for="column in columns"
          v-show="dialogMode === 'edit' || !isAutoGeneratedColumn(column.column_name)"
          :key="column.column_name"
          :label="column.column_name"
          :required="isColumnRequired(column.column_name)"
        >
          <!-- Boolean checkbox -->
          <el-checkbox
            v-if="getColumnType(column.column_name) === 'boolean'"
            v-model="formData[column.column_name]"
          />
          
          <!-- Date picker -->
          <el-date-picker
            v-else-if="isDateType(getColumnType(column.column_name))"
            v-model="formData[column.column_name]"
            type="date"
            placeholder="Выберите дату"
            value-format="YYYY-MM-DD"
          />
          
          <!-- Text input (default) -->
          <el-input
            v-else
            v-model="formData[column.column_name]"
            :disabled="column.column_name === primaryKey && dialogMode === 'edit'"
            :placeholder="isColumnRequired(column.column_name) ? 'Обязательное поле' : 'Опционально'"
          />
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="dialogVisible = false">Отмена</el-button>
        <el-button type="primary" @click="handleSave">Сохранить</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { Plus, Refresh, Search, Edit, Delete, ArrowUp } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getTableSchema, getTableData, createRow, updateRow, deleteRow } from '@/api/tables'
import { useSchemaStore } from '@/stores/schema'

const route = useRoute()
const schema = ref(route.params.schema)
const tableName = ref(route.params.tableName)

const schemaStore = useSchemaStore()

const loading = ref(false)
const columns = ref([])
const rawTableData = ref([])
const primaryKey = ref('id')
const searchQuery = ref('')
const selectedColumn = ref('')
const sortColumn = ref('')
const sortOrder = ref('') // '', 'asc', 'desc'
const expandedCells = ref(new Set()) // Track expanded cells

// Helper function to toggle cell expansion
const toggleCellExpansion = (rowIndex, columnName) => {
  const key = `${rowIndex}-${columnName}`
  if (expandedCells.value.has(key)) {
    expandedCells.value.delete(key)
  } else {
    expandedCells.value.add(key)
  }
}

// Track cell DOM references to check if text is truncated
const cellRefs = ref({})

// Helper function to check if text is truncated
const isTextTruncated = (cellKey) => {
  const el = cellRefs.value[cellKey]
  if (!el) return false
  return el.scrollWidth > el.clientWidth || el.scrollHeight > el.clientHeight
}

// Helper function to get column type
const getColumnType = (columnName) => {
  const column = columns.value.find(col => col.column_name === columnName)
  return column && column.data_type ? String(column.data_type).toLowerCase() : 'text'
}

// Helper function to check if column is numeric
const isNumericType = (dataType) => {
  const numericTypes = ['integer', 'bigint', 'smallint', 'numeric', 'decimal', 'real', 'double precision', 'money', 'serial', 'bigserial', 'smallserial']
  return numericTypes.includes(dataType)
}

// Helper function to check if column is date/time
const isDateType = (dataType) => {
  const dateTypes = ['date', 'timestamp', 'timestamp without time zone', 'timestamp with time zone', 'time', 'time without time zone', 'time with time zone']
  return dateTypes.includes(dataType)
}

const isArrayType = (dataType) => {
  return dataType === 'array' || dataType.endsWith('[]')
}

// Helper function to check if column is required (NOT NULL constraint)
const isColumnRequired = (columnName) => {
  const column = columns.value.find(col => col.column_name === columnName)
  return column && column.is_nullable === "NO"
}

// Helper function to check if column is auto-generated (has sequence default)
const isAutoGeneratedColumn = (columnName) => {
  const column = columns.value.find(col => col.column_name === columnName)
  if (!column || typeof column.column_default !== 'string') return false
  
  const defaultValue = column.column_default.toLowerCase()
  const autoGenPatterns = [
    'nextval',           // Serial sequences (serial, bigserial, smallserial)
    'gen_random_uuid',   // UUID generation
    'uuid_generate_v1',  // UUID extension v1
    'uuid_generate_v4',  // UUID extension v4
    'gen_random_bytes',  // Random bytes
    'now()',             // Current timestamp (often auto-set)
    'current_timestamp', // Current timestamp
    'current_date',      // Current date
    'current_time',      // Current time
  ]
  
  return autoGenPatterns.some(pattern => defaultValue.includes(pattern.toLowerCase()))
}

const detectPrimaryKey = (cols) => {
  if (!Array.isArray(cols) || cols.length === 0) return 'id'

  const byFlag = cols.find(col => col.is_primary_key)
  if (byFlag?.column_name) return byFlag.column_name

  const byDefault = cols.find(col => typeof col.column_default === 'string' && col.column_default.includes('nextval'))
  if (byDefault?.column_name) return byDefault.column_name

  const byName = cols.find(col => col.column_name === 'id')
  if (byName?.column_name) return byName.column_name

  const bySuffix = cols.find(col => col.column_name.endsWith('_id'))
  if (bySuffix?.column_name) return bySuffix.column_name

  return cols[0].column_name
}

const formatArrayForInput = (value) => {
  if (!Array.isArray(value)) return value
  const escaped = value.map(item => String(item).replace(/"/g, '\\"'))
  return `{${escaped.map(item => `"${item}"`).join(',')}}`
}

const parseArrayFromInput = (value) => {
  if (!value || typeof value !== 'string') return value
  const trimmed = value.trim()
  if (!trimmed.startsWith('{') || !trimmed.endsWith('}')) return value
  const inner = trimmed.slice(1, -1).trim()
  if (!inner) return []
  const parts = inner.split(/","/)
  return parts.map(part => part.replace(/^"/, '').replace(/"$/, '').replace(/\\"/g, '"'))
}

// Computed filtered and sorted data
const tableData = computed(() => {
  let result = [...rawTableData.value]
  
  // Apply filtering
  if (searchQuery.value && selectedColumn.value) {
    const query = searchQuery.value.toLowerCase()
    result = result.filter(row => {
      const cellValue = row[selectedColumn.value]
      if (cellValue === null || cellValue === undefined) return false
      return String(cellValue).toLowerCase().includes(query)
    })
  }
  
  // Apply sorting
  if (sortColumn.value && sortOrder.value) {
    const columnType = getColumnType(sortColumn.value)
    
    result.sort((a, b) => {
      const aVal = a[sortColumn.value]
      const bVal = b[sortColumn.value]
      
      // Handle null/undefined values
      if (aVal === null || aVal === undefined) return sortOrder.value === 'asc' ? 1 : -1
      if (bVal === null || bVal === undefined) return sortOrder.value === 'asc' ? -1 : 1
      
      // Numeric comparison
      if (isNumericType(columnType)) {
        const aNum = Number(aVal)
        const bNum = Number(bVal)
        return sortOrder.value === 'asc' ? aNum - bNum : bNum - aNum
      }
      
      // Date comparison
      if (isDateType(columnType)) {
        const aDate = new Date(aVal)
        const bDate = new Date(bVal)
        return sortOrder.value === 'asc' ? aDate - bDate : bDate - aDate
      }
      
      // Boolean comparison
      if (columnType === 'boolean') {
        const aBool = aVal === true || aVal === 'true' || aVal === 't'
        const bBool = bVal === true || bVal === 'true' || bVal === 't'
        if (aBool === bBool) return 0
        return sortOrder.value === 'asc' ? (aBool ? 1 : -1) : (aBool ? -1 : 1)
      }
      
      // String comparison (default)
      const aStr = String(aVal).toLowerCase()
      const bStr = String(bVal).toLowerCase()
      
      if (sortOrder.value === 'asc') {
        return aStr.localeCompare(bStr)
      } else {
        return bStr.localeCompare(aStr)
      }
    })
  }
  
  return result
})

const pagination = ref({
  page: 1,
  limit: 50,
  total: 0
})

const dialogVisible = ref(false)
const dialogMode = ref('add') // 'add' or 'edit'
const formData = ref({})

const loadSchema = async () => {
  try {
    const response = await getTableSchema(schema.value, tableName.value)
    console.log('Schema response:', response)
    columns.value = response.data.columns
    primaryKey.value = detectPrimaryKey(columns.value)
  } catch (error) {
    console.error('Schema error:', error)
    ElMessage.error('Ошибка загрузки схемы таблицы')
  }
}

const handleSort = (columnName) => {
  if (sortColumn.value === columnName) {
    // Cycle through: asc -> desc -> none
    if (sortOrder.value === 'asc') {
      sortOrder.value = 'desc'
    } else if (sortOrder.value === 'desc') {
      sortOrder.value = ''
      sortColumn.value = ''
    }
  } else {
    sortColumn.value = columnName
    sortOrder.value = 'asc'
  }
}

const loadData = async () => {
  loading.value = true
  try {
    const params = {
      page: pagination.value.page,
      limit: pagination.value.limit
    }
    
    const response = await getTableData(schema.value, tableName.value, params)
    rawTableData.value = response.data
    
    const paginationData = response.pagination
    pagination.value = {
      page: Number(paginationData.page),
      limit: Number(paginationData.limit),
      total: Number(paginationData.total),
      totalPages: Number(paginationData.totalPages)
    }
  } catch (error) {
    console.error('Data error:', error)
    ElMessage.error('Ошибка загрузки данных')
  } finally {
    loading.value = false
  }
}

const handleAdd = () => {
  dialogMode.value = 'add'
  const data = {}
  // Initialize form with default values
  columns.value.forEach(col => {
    if (col.column_default) {
      // Parse default value
      let defaultValue = col.column_default
      // Remove function calls and quotes
      if (defaultValue.includes('::')) {
        defaultValue = defaultValue.split('::')[0]
      }
      defaultValue = defaultValue.replace(/^'|'$/g, '').trim()
      
      // Don't set auto-generated defaults
      if (!isAutoGeneratedColumn(col.column_name)) {
        data[col.column_name] = defaultValue
      }
    }
  })
  formData.value = data
  dialogVisible.value = true
}

const handleEdit = (row) => {
  dialogMode.value = 'edit'
  const data = {}
  columns.value.forEach(col => {
    const type = getColumnType(col.column_name)
    const value = row[col.column_name]
    data[col.column_name] = isArrayType(type) ? formatArrayForInput(value) : value
  })
  formData.value = data
  dialogVisible.value = true
}

const handleSave = async () => {
  try {
    const payload = { ...formData.value }
    columns.value.forEach(col => {
      const type = getColumnType(col.column_name)
      if (isArrayType(type)) {
        payload[col.column_name] = parseArrayFromInput(payload[col.column_name])
      }
    })

    if (dialogMode.value === 'add') {
        console.log('Creating new row with payload:', payload)
      await createRow(schema.value, tableName.value, payload)
      ElMessage.success('Запись добавлена')
    } else {
      const id = payload[primaryKey.value]
      console.log('Updating row with ID:', primaryKey, 'Payload:', payload)
      await updateRow(schema.value, tableName.value, id, payload)
      ElMessage.success('Запись обновлена')
    }
    
    dialogVisible.value = false
    loadData()
  } catch (error) {
    ElMessage.error('Ошибка сохранения')
  }
}

const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm(
      'Вы уверены, что хотите удалить эту запись?',
      'Подтверждение',
      {
        confirmButtonText: 'Удалить',
        cancelButtonText: 'Отмена',
        type: 'warning'
      }
    )
    
    const id = row[primaryKey.value]
    await deleteRow(schema.value, tableName.value, id)
    ElMessage.success('Запись удалена')
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('Ошибка удаления')
    }
  }
}

const formatValue = (value) => {
  if (value === null || value === undefined) return '-'
  if (typeof value === 'boolean') return value ? 'Да' : 'Нет'
  if (typeof value === 'object') return JSON.stringify(value)
  return value
}

// Helper function to log table access
const logTableAccess = () => {
  const key = `table_access_${schema.value}`
  let history = []
  
  try {
    const stored = localStorage.getItem(key)
    if (stored) {
      history = JSON.parse(stored)
    }
  } catch (e) {
    console.error('Error reading localStorage:', e)
  }
  
  // Remove if exists and add to beginning (most recent)
  history = history.filter(t => t !== tableName.value)
  history.unshift(tableName.value)
  
  // Keep only last 20
  history = history.slice(0, 20)
  
  try {
    localStorage.setItem(key, JSON.stringify(history))
    // Trigger update in other components
    schemaStore.triggerTableAccessUpdate()
  } catch (e) {
    console.error('Error writing to localStorage:', e)
  }
}

onMounted(async () => {
  logTableAccess()
  await loadSchema()
  await loadData()
})
</script>

<style scoped>
.table-editor {
  width: 100%;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  gap: 10px;
}

.filters {
  display: flex;
  align-items: center;
}

:deep(.el-table__cell) {
  text-align: left !important;
}

.table-cell-content {
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  display: block;
}

.table-cell-expanded {
  white-space: normal;
  word-break: break-word;
  display: flex;
  align-items: flex-start;
  gap: 8px;
}

.expand-icon {
  flex-shrink: 0;
  margin-top: 2px;
}

:deep(.table-tooltip) {
  max-width: 500px !important;
}

:deep(.table-tooltip .el-popper__content) {
  word-break: break-word;
  white-space: normal;
}

:deep(.el-popper.is-dark[role="tooltip"]) {
  max-width: 500px !important;
}

:deep(.el-tooltip__popper) {
  max-width: 500px !important;
}
</style>

<style>
.table-tooltip,
.table-tooltip .el-popper,
.table-tooltip.el-tooltip__popper {
  max-width: 500px !important;
  width: 500px !important;
}
</style>
